# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to optimize the NVCModel 
#' @param y N vector of observations
#' @param mu mean vector (N dimensional)
#' @param U PQ x Q matrix of P Variance Components
#' @param ellinit P vector of initialization values for ell
#' @details Fits the following model (for unknown ell)
#'   \deqn{y ~ N(mu, e^{ell_1}U_1 + ...+ e^{ell_P}U_1)}
#' using L-BFGS optimization implemented in optimized C++ code. 
#' @return List: LogLik is log likelihood at optimima. Pars argument is ells. 
#' @export
#' @md
#' @examples
#'   N <- 1000
#'   I <- diag(N)
#'   U1 <- diag(N)
#'   U2 <-  rWishart(1, N+10, diag(N))[,,1]
#'   ell <- c(0.0001, 3)
#'   Sigma <- exp(ell[1])*U1 + exp(ell[2])*U2
#'   L <- t(chol(Sigma))
#'   mu <- rep(4, N)
#'   y <- mu + L %*% rnorm(N) 
#'   fit <- optimNVC(y, mu, rbind(U1, U2), c(0,0))
optimNVC <- function(y, mu, U, ellinit) {
    .Call('_NVC_optimNVC', PACKAGE = 'NVC', y, mu, U, ellinit)
}

