# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to optimize the NVCModel 
#' @param y N vector of observations
#' @param mu mean vector (N dimensional)
#' @param U PQ x Q matrix of P Variance Components
#' @param ellinit P vector of initialization values for ell
#' @details Fits the following model (for unknown ell)
#'   \deqn{y ~ N(mu, e^{ell_1}U_1 + ...+ e^{ell_P}U_1)}
#' using L-BFGS optimization implemented in optimized C++ code. 
#' @return List: LogLik is log likelihood at optimima. Pars argument is ells. 
#' @export
#' @md
optimNVC <- function(y, mu, U, ellinit) {
    .Call('_NVC_optimNVC', PACKAGE = 'NVC', y, mu, U, ellinit)
}

